cargo: update time to fix compilation issue
As of Rust 1.80, time v0.3.34 no longer builds, failing with the
following:

    error[E0282]: type annotations needed for `Box<_>`
      --> /.../time-0.3.34/src/format_description/parse/mod.rs:83:9
       |
    83 |     let items = format_items
       |         ^^^^^
    ...
    86 |     Ok(items.into())
       |              ---- type must be known at this point
       |
    help: consider giving `items` an explicit type, where the placeholders `_` are specified
       |
    83 |     let items: Box<_> = format_items
       |              ++++++++

Updating seems to help.

    $ cargo update time
        Updating crates.io index
        Updating time v0.3.34 -> v0.3.36